[package]
name = "xchannel"
version = "2.1.1"
edition = "2024"
description = "mmap-backed IPC channels with regionized layout, alignment-safe headers, and file rolling."
license = "MIT"
readme = "README.md"
repository = "https://github.com/dkumsh/xchannel"
keywords = ["mmap", "ipc", "zero-copy", "shared-memory", "channels"]
categories = ["concurrency", "memory-management", "os::unix-apis", "data-structures"]
include = [
    "src/**",
    "CHANGELOG.md",
    "README.md",
    "LICENSE*",
    "Cargo.toml",
    "tests/**"
]

[lib]
name = "xchannel"
path = "src/lib.rs"

[dependencies]
memmap2 = "0.9.5"
libc = "0.2.170"

[dev-dependencies]
anyhow = "1.0.96"
clap = { version = "4.5.51", features = ["derive"] }
hdrhistogram = "7.5.4"
